version: '3.8'
services:
  # PostgreSQL Database
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: emailanalytics
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Backend Application
  backend:
    build: .
    ports:
      - "5000:5000"
    environment:
      NODE_ENV: development
      DATABASE_URL: postgresql://postgres:password@postgres:5432/emailanalytics
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      VITE_AZURE_CLIENT_ID: ${VITE_AZURE_CLIENT_ID}
      VITE_AZURE_TENANT_ID: ${VITE_AZURE_TENANT_ID}
      JWT_SECRET: your-jwt-secret-for-development
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - .:/app
      - /app/node_modules

volumes:
  postgres_data: